using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Refit.Composite.SourceGenerator;

[Generator]
public class CompositeApiGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is InterfaceDeclarationSyntax,
                transform: (tuple, _) => {
                    var interfaceSyntax = (InterfaceDeclarationSyntax)tuple.Node;
                    if (tuple.SemanticModel.GetDeclaredSymbol(interfaceSyntax) is INamedTypeSymbol symbol) {
                        if (symbol.AllInterfaces.Any(i => i.Name == "IRefitComposite")) {
                            return symbol;
                        }
                    }

                    return null;
                })
            .Where(x => x != null);

        context.RegisterSourceOutput(interfaceDeclarations.Collect(), (spc, symbols) => {
            foreach (var symbol in symbols.Distinct(SymbolEqualityComparer.Default)) {
                if (symbol is not INamedTypeSymbol validSymbol) continue;

                var generatedCode = GenerateExtensionClass(validSymbol);
                spc.AddSource($"{symbol.Name}Registration.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        });
    }

    private static string GenerateExtensionClass(INamedTypeSymbol interfaceSymbol)
    {
        var namespaceSymbol = interfaceSymbol.ContainingNamespace;
        var isGlobalNamespace = namespaceSymbol == null || namespaceSymbol.IsGlobalNamespace;
        var namespaceName = isGlobalNamespace ? "" : namespaceSymbol?.ToDisplayString();

        var interfaceName = interfaceSymbol.Name;
        var className = $"{interfaceName.Substring(1)}Generated";

        var properties = interfaceSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => !p.IsWriteOnly)
            .ToList();

        var format = SymbolDisplayFormat.FullyQualifiedFormat;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Threading;");
        if (!isGlobalNamespace) {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        var fullInterfaceName = interfaceSymbol.ToDisplayString(format);
        sb.AppendLine($"public sealed class {className} : {fullInterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly System.IServiceProvider _serviceProvider;");
        sb.AppendLine();

        foreach (var prop in properties) {
            sb.AppendLine($"    private object? _cached{prop.Name};");
        }

        sb.AppendLine();

        foreach (var prop in properties) {
            var typeName = prop.Type.ToDisplayString(format);
            sb.AppendLine($"    public {typeName} {prop.Name}");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (_cached{prop.Name} is {typeName} initialized) return initialized;");
            sb.AppendLine();
            sb.AppendLine($"            var service = _serviceProvider.GetRequiredService<{typeName}>();");
            sb.AppendLine($"            global::System.Threading.Interlocked.CompareExchange(ref _cached{prop.Name}, service, null);");
            sb.AppendLine($"            return ({typeName})_cached{prop.Name}!;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof(global::System.Object))]");
        sb.AppendLine($"    public {className}(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");

        return sb.ToString();
    }
}
